zentyal/sogo

OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStoreObject.m
OpenChange/MAPIStoreTasksMessage.m
OpenChange/MAPIStoreTypes.m
OpenChange/iCalEvent+MAPIStore.m

Thus the associated timezone is UTC.
Adjusting properties which shift the date are now reverted and some fixed according to specs. See the following table for details:
* `PidTagSubmitTime` (Sent field in the mail) is now set properly
* Use UTC date in `date` field in MIME message (RFC 822)
* Fix start, end and complete dates for tasks
* Fix start, end and replace time for calendar events (This should fix the exception shifting)

Use PT_SYSTIME as absolute timestamp

---

OpenChange/MAPIStoreFolder.m

Calling deleteFolder message to actually remove it from DB/IMAP
depending on the class.

oc: Remove a source folder on move folder operation

---

OpenChange/MAPIStoreMailFolder.m

The URL was incorrectly set when any of ;/?:@&=+$,# was used
in the folder name.

oc-mail: Move mail folders with reserved chars

---

OpenChange/MAPIStoreFolder.m

Two different indexing entries were created on move operation making
impossible to restore old folder position in the original parent folder.
This was due to cleanupCaches message calls to objectId which requires
to have the indexing entry available.
Use case:
* Restore a folder from "Deleted items" folders

oc: Move back and forth folders now are in sync

---

OpenChange/MAPIStoreDBFolder.m
OpenChange/MAPIStoreMailFolder.m
SoObjects/SOGo/SOGoCacheGCSFolder.h
SoObjects/SOGo/SOGoCacheGCSFolder.m
SoObjects/SOGo/SOGoObject.h

The path attribute from `SOGoCacheGCSFolder` is properly updated
in the database but not when returning from `path` message as
the container is the old one.

oc: Set right container in dbFolder when moving a folder

---

OpenChange/MAPIStoreContext.m
OpenChange/MAPIStoreFallbackContext.m

Due to https://github.com/openchange/openchange/pull/204.
Until it is published by OC or dismissed.

oc: Use dlinklist from samba for now

---

OpenChange/MAPIStoreDBFolder.m
OpenChange/MAPIStoreMailFolder.m

Once openchange/openchange#200 is merged, a NULL pointer can be passed as target folder in move folder operation, then we can become the moved folder into a root folder.
By now, it is only implement for MAPIStoreMailFolder and MAPIStoreDBFolder (Notes, Journal) as MAPIStoreGCSFolder does not implement to have subfolders and it is assumed throughout SOGo code the subfolders have the same role that its parent has.

Move subfolder (Mail, Journal, Notes) to root

---

OpenChange/MAPIStoreDBMessage.m

Without this outlook clients with custom views set on folders will crash because this are needed properties and were not being saved.

Support custom views on folders

---

OpenChange/MAPIStoreAppointmentWrapper.m
OpenChange/iCalEvent+MAPIStore.m

See [MS-OXCICAL] Section 2.1.3.1.1.20.3 for details.
It requires https://github.com/openchange/openchange/pull/216 to retrieve
the value from MAPI client

oc-calendar: Implement categories to share the colour

---

OpenChange/MAPIStoreContactsMessage.m

The implemented fields persist now from Outlook to Outlook:
* Profession
* Manager's name
* Assistant's name
* Spouse/Partner's name
* Office (implemented as the custom type X-MS-OFFICE)

Save missing contact properties in database

---

NEWS
OpenChange/GNUmakefile
OpenChange/MAPIStoreCalendarFolder.m
OpenChange/MAPIStoreMailAttachment.m
OpenChange/MAPIStoreMailMessage.h
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStoreSharingMessage.h
OpenChange/MAPIStoreSharingMessage.m

By implementing the Sharing Message object (`MAPIStoreSharingMessage`) as a proxy of `MAPIStoreMailMessage` storing the sharing properties from [MS-OXSHARE] as eXtensible MIME headers of the mail.
In addition to this, it is required to have custom properties values when the attached file is called `sharing_metadata.xml` as described in [MS-OXWSMSHR] Section 3.1.1.
It requires https://github.com/openchange/openchange/pull/223 to work.

Give support to calendar sharing invitation

---

NEWS
OpenChange/MAPIStoreMailVolatileMessage.m

But it has recipients. This is for sure happening with event invitations messages and when the recipient list does not include `orig` key.

oc-mail: Set sender on email messages without an orig recipient

---

NEWS
OpenChange/RTFHandler.m

Be able to parse safely `\*\xxxxx` control words (they are just ignored) with `\bin` elements inside it.
This is a rewrite of the `parsePicture` function (which was wrong) and make it generic to parse anything.

oc-rtf: safe parse ignoring content

---

NEWS
OpenChange/MAPIStoreMailFolder.m

This makes sent mails are not longer automatically copied
to Drafts folder.
Reasoning:
When Outlook sends a mail, OpenChange submits the message and
copy the message to Drafts folder. Afterwards, the client asks
to move this message using SyncImportMessageMove ROP from
Drafts to Sent. During this movement, the message is unregistered
from the indexing database. If the client has updated Drafts
folder before that movement, then the client will keep this
message as the MID is not returned in oxcfxics download sync
as deleted. Setting the message as soft deleted, make it work.

oc-mail: Register source message as soft deleted on movement

---

NEWS
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailMessage.h
OpenChange/MAPIStoreMailMessage.m

In this way, we do not modify the flags (\Seen) on preloading.
The IMAP server returns the content without .peek section so
it is removed.
This also performs the modification intended by the following
Pull Request (#50) that tried to avoid set \Seen flag when preloading message bodies
on synchronisation. But in this case we are not incrementing the
modseq as we are not modifying any messages flags.
Thanks to @figarocorso  for the hint past October 2014.

Use body.peek to preload message bodies

---

NEWS
OpenChange/RTFHandler.m

Be able to parse rtf files without `\colortbl` control word

oc-rtf: no color table definition

---

NEWS
OpenChange/iCalEvent+MAPIStore.m

Outlook sets recipient type of Required attendees as MAPI_TO and
optional ones as MAPI_CC, so the fix is just to not only iterate
over the "to" list of recipients but also the "cc" one. We're
also setting the proper iCal value for this case (OPT-PARTICIPANT
instead of REQ-PARTICIPANT)

oc-calendar: Fix event invitations for optional attendees

---

OpenChange/MAPIStoreFolder.m

The `[SOGoFolder:aclUsers]` returns a reference to a `NSArray`
which is being modified in the `for` loop making fail when
more than one user is in the ACL with `NSRangeException`.
NEWS message to include after merge in *Bug fixes* section:
```
- Fix setting permissions for a folder with several users
```

oc: Empty ACL from a folder works with several users

---

OpenChange/MAPIStoreCalendarMessage.m

A failure in parsing an ICS makes return a nil calendar
object. Instead of creating an appointment with nil
information which can lead to crashes like the one
generated creating PidLidCleanGlobalObjectId property.
We return an empty message with no information which is
taken into account in Outlook but not displayed like
in SOGo webmail does.
`NEWS` suggestion line in *Bug fixes* section:
* Fix server-side crash with invalid events

oc-calendar: do not crash with invalid events

---

OpenChange/MAPIStoreMailFolder.h
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStoreSharingMessage.h
OpenChange/MAPIStoreSharingMessage.m

This requires https://github.com/openchange/openchange/pull/244 to work but basically we have modified this backend to store request-related properties in a `MAPIStoreMailMessage` using the versions message from the `MAPIStoreMailFolder` container and fix the setter/getter for the following properties:
* PidNameXSharingFlavor
* PidLidSharingFlavor
* PidNameXSharingCapabilities
* PidLidSharingResponseType
* PidLidSharingResponseTime
NEWS message proposal in *Enhancements* section:
```
Sharing request among different Outlook versions
```
This must work with any kind of folder thanks to https://github.com/openchange/openchange/pull/247

Calendar sharing request among different Outlook versions

---

OpenChange/MAPIStoreMailFolder.m

As it happened with dba17fb if we interleave requests
from different users while creating a folder we can
create the folder in other user's mailbox as latest
activeUser is the one from latest sogo_context_get_root_folder
call.
This is for me a lack of right design and a workaround
only fixing this issue but not the root cause.
Proposed `NEWS` line in **Bug fixes** section:
* Does not create a mail folder in other user's mailbox

oc-mail: Ensure we are creating folder to the right user

---

OpenChange/MAPIStoreSOGo.m

Avoiding the usage of __FUNCTION__ and __LINE__
and more related with the logging system is being in place
for OpenChange.
As well as set the proper level to some debug messages.

oc: Use new OC_DEBUG macro

---

NEWS
OpenChange/MAPIStoreMailMessage.m

This property is needed to show the 'Internet Headers' in Outlook.
Outlook show them in the properties dialog of a message.
The property is defined in [MS-OXOMSG] section 2.2.1.61.
The property is formed concatenating the mail message headers.
The headers are appended in no defined order, no order is defined in
the specification and I do not see any reason for the order used in
Outlook.

Support for PidTagTransportMessageHeaders property

---

OpenChange/MAPIStoreMailFolder.m

1. Return soft-deleted mails while syncing
2. Include Deleted flagged messages on syncing the cache
The second one I don't know if it is required but increase accuracy to the cache values.
Use case: Moving messages around in one Outlook profile are correctly synced in other Outlook profile for the same account.
Use case: Drafts folder is correctly synced when sending mails leaving the folder empty when a message is successfully sent in all cases.
Tentative `NEWS` line could be already partial patch and this one:
- Sent mails are not longer in Drafts folder using Outlook
- Deleted mails are properly synced between Outlook profiles from the same account

Soft deleted mail messages sync

---

ActiveSync/SOGoActiveSyncDispatcher.m
OpenChange/MAPIStoreUserContext.m
Tools/SOGoToolManageEAS.m

Use full login for `sogo_cache_folder` tables.
So when multidomain is enabled we will have tables like `sogo_cache_folder_user_A_domain_D_com` instead of just `sogo_cache_folder_user`
If multidomain is disabled the folders will still be like `sogo_cache_folder_user`

Multidomain cache tables

---

OpenChange/MAPIStoreCalendarMessageTable.m
OpenChange/MAPIStoreContactsMessageTable.m
OpenChange/MAPIStoreTasksMessageTable.m

This change is required as oxcfxics is asking for sorting
using this property.
We fake this property on GCS folders (Tasks, Calendar, Contacts)
using c_lastmodified column.
Suggestion for `NEWS` file in **Enhancements** section:
- Events, tasks and contacts are synced in reverse chronological order

oc: return last modified messages when sorted by PidMessageTagDeliveryTime

---

OpenChange/MAPIStoreFolder.m
OpenChange/MAPIStoreMapping.h
OpenChange/MAPIStoreMapping.m

We believe the folder ID OpenChange is sending us is new
and we keep the indexing database properly updated.
Although the solution is not elegant, this could avoid
inconsistencies between what the client stores and the
relation in the MAPIStore backend.

oc: Enforce the folder creation mapping when the FID exists

---

SoObjects/SOGo/EOQualifier+SOGoCacheObject.m

sogo-openchange library stores the properties as NSString keys
and the search function casts the values to NSNumber, which it may
be valid for other parts but not for this library.
The real fix would be to store the property keys as NSNumbers as
they are uint32_t at the end. However, this may lead to a great
refactor in the library.
With this fix, we can match the search for a property in a
MAPIStoreFallback folder, such as Notes or Deleted Items, or
MAPIStoreFolder properties (ie: search for a subfolder) or
for MAPIStoreFAIMessages in a folder.

oc: Search for properties in a SOGoMAPIDB object now works

---

OpenChange/MAPIStoreAppointmentWrapper.m

Take into account optional attendees setting the recipient
type to MAPI_CC when they have the iCal role set to OPT-PARTICIPANT
instead of harding always MAPI_TO (required) as was done before.
This is a complementary fix for: #108
NEWS message to include after merge in *Bug fixes* section:
```
- Optional attendes are now shown as optional in calendar invitations
```

oc-calendar: Fix recipient type for invitations

---

OpenChange/MAPIStoreAppointmentWrapper.m
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStoreSamDBUtils.m
SoObjects/SOGo/SOGoUserManager.m

All this basically is to make it work on multidomain environment the `Reply all` functionality of emails but I'm sure there are more use cases as an Outlook client that don't work nowadays without this patch.
Suggested message for `NEWS`, under bugfix seciton:
* Outlook clients can use reply all functionality on multidomain environment
I don't know how to put into words properly zinc environment / multidomain environment / email adress as login.
More info on commit message but basically it was that we were using `user` instead of `user@domain.com` in several places.

oc: Fix internal EntryIds properties on multidomain

---

OpenChange/MAPIStoreContext.m

This is done by OpenChange after this patchset is merged:
https://github.com/openchange/openchange/pull/273
This is a long term to fix by removing all indexing code in SOGo backend.

oc: Do not create indexing entry for a root folder

---

OpenChange/MAPIStoreAppointmentWrapper.m

All-day events' dates are stored in floating time (withouth time zone information), so when time zone information is required we have to extract it from the user's context. Some properties, on the other hand, are relative to the user's time zone, so no extra computations are required.
* https://github.com/Zentyal/sogo/commit/7e89c43919a258dc4f41d309b58408dab307b6d5 Fixes the way all-day recurring events are displayed in OL (they were displayed from 2:00 to 2:00 of the following day)
* https://github.com/Zentyal/sogo/commit/ebe2a466e7ac3d6aa0f10befc9367555224ac752 Doesn't produce any visible behaviour change, but it corrects a mismatch between the specifications and the code.
Suggested NEWS line:
`Recurrent all day events are now shown properly in Outlook`

oc-calendar: Interpret dates of all-day events in floating time

---

OpenChange/GNUmakefile
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailFolderTable.h
OpenChange/MAPIStoreMailFolderTable.m

This allows us to search for a subfolder in a mail
folder successfully. This is happening ie on folder creation.
I see this not relevant from the user's point of view as you can see the folders that exists before trying to create a new one with the same name. This is only useful by now for functional testing. Correct me if I'm wrong.

oc-mail: Support restricitions on name for MAPIStoreMailFolderTable

---

OpenChange/MAPIStoreMailContext.m
OpenChange/MAPIStoreMailFolder.m

This fixes two scenarios:
* An IMAP subfolder has updated its hierarchy when it is asked
to be synchronised
* An IMAP root folder is created on Outlook when you logon. OpenChange
changes are required to be refreshed on synchronisation.
I'd add this in **Enhancements** section of `NEWS` file as it can be workarounded by restarting samba daemon. These two lines should be added:
* Mail subfolders created in WebMail are created when Outlook synchronises.
* Mail root folder created in WebMail (same level INBOX) are created on Outlook logon.

oc-mail: Flush IMAP hierarchy cache to update Outlook folders

---

OpenChange/MAPIStoreMailMessage.h
OpenChange/MAPIStoreMailMessage.m

The value of `PidTagResponseRequested` property in the invitation mail
wasn't being set properly, while the `PidTagReplyRequested` property
wasn't being set at all. This caused invitation response mails not to be
sent. Both properties are expected to be `true`.
Suggested NEWS line:
`Event invitation response mails are now sent`

oc-calendar: Fix property values of invitation responses

---

OpenChange/MAPIStoreAppointmentWrapper.m

Introduced by ebe2a466e7 in PR #132 when the event is not
all day neither recurrent one.
The fix is just to initialise to nil when it is a normal event
and it returns NOT_FOUND for this property.
No update in `NEWS` as it is a fix on a one of the unreleased changes.

oc-calendar: Fix regression on PidLidAppointmentTimeZoneDefinitionStartDisplay

---

SoObjects/SOGo/SOGoUserManager.m

Right now it tries to authenticate against all ldap sources. So if you have 200 companies with 1 ldap source per company (and the user trying to authenticate belongs the last of that list) it will try to authenticate against 200 ldaps.
With this patch it will try to authenticate only against the sources of that domain (1 in this case)

Try to authenticate only against sources of the given domain

---

SoObjects/SOGo/SOGoUserFolder.m
SoObjects/SOGo/SOGoUserManager.m
UI/MainUI/SOGoRootPage.m

There are two fixes here, one is mayor and the other is minor. Both only applies for multidomain sogo scenario and are issues related with cached data related with logged users.
* Avoid creating cache entries like `user+attributes` (in case you logged in as, e.g., `user@foo.com`) to avoid reading emails from another user with same name but from different domain (e.g. `user@bar.com`).
* Avoid creating cache entries like `user@domain@domain+attributes`, no need to create that, there was being dup info (same contents that `user@domain+attributes` entries, depending of the method one of those was being read/written).
I'll let as exercise to the reader to determine which one is the mayor and which the minor one.
Suggested change to `NEWS` under `bug fix` section:
`Fixed reading emails from …

Avoid reading emails from other domains (info@foo vs info@bar)

---

SoObjects/SOGo/BSONCodec.m

Using name abbreviation in Objective-C is discouraged
as it stated in the following link:
https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSTimeZone_Class/index.html#//apple_ref/occ/clm/NSTimeZone/timeZoneWithAbbreviation:
Indeed, the GNUStep library is generating the name
abbreviation using the system tzdata information
but parsing this data using GNUStep resources making
changes like this:
http://mm.icann.org/pipermail/tz-announce/2014-August/000023.html
Not working until GNUStep reaches these tzdata changes.
Using the UTC offset we are losing the position in planet
Earth but it could be considered valid looking at other
bson implementations.
Suggested entry to `NEWS` in *Bug fixes* section:
* Dates stored in metadata works along …

Use UTC offset to encode NSCalendarDate in BSON

---

UI/Templates/MailerUI/UIxMailMainFrame.wox

This was left unremoved in this commit 01c63197  leading to errors like the one described here: https://tracker.zentyal.org/issues/3511

Remove left menus after labels removal

---

SoObjects/SOGo/SOGoSession.m

This was crashing with invalid value (shorter than it should be or nil value).

Safe decoding of secured value

---

Tools/GNUmakefile
Tools/SOGoToolCreateFolder.m
Tools/SOGoToolRestore.h
Tools/SOGoToolRestore.m

Changes in logs (thanks to sixstone) :
Apart from the above comments, as this includes user-level changes, I'd suggest to add two lines to NEWS, one for New features:
Added create-folder subcommand to sogo-tool to create contacts and calendar folders
And one for Bug fixes:
sogo-tool now works in multidomain environments.

sogo-tool: Added create-folder command

---

OpenChange/MAPIStoreMessage.m

Before this change, the recipient address was only extracted from the sogo user object.
This made mail to groups undeliverable. Now if we do not have mail addresses
from user object, we try to use parameters from the client call.

mapistore: can use client data to get recipient address

---

OpenChange/MAPIStoreMessage.m

This is crashing when the PidTagObjectType property is set for
some recipient and not for others.
If the property is missing, then no object type for the recipient
is assumed.
This fixes a regression on #100.
No updated NEWS is required as this change hasn't been released.

oc: Check PidTagObjectType before dereferencing on ModifyRecipients

---

OpenChange/MAPIApplication.h
OpenChange/MAPIApplication.m
OpenChange/MAPIStoreCalendarFolder.m
OpenChange/MAPIStoreCalendarMessage.m
OpenChange/MAPIStoreContactsFolder.m
OpenChange/MAPIStoreContext.m
OpenChange/MAPIStoreDBFolder.m
OpenChange/MAPIStoreFolder.m
OpenChange/MAPIStoreGCSBaseContext.m
OpenChange/MAPIStoreMailContext.m
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStoreSOGo.m
OpenChange/MAPIStoreTasksFolder.m
OpenChange/MAPIStoreUserContext.h
OpenChange/MAPIStoreUserContext.m

Two main fixes:
1. Disable current user context when an operation has ended.
2. Enable user context before creating sogo objects.
Without this there were situations where you could use an imap connection from another user because some objects were created with a WOContext with an active user different of the current one (but from a previous request).
Suggested messages for NEWS:
* Fixed several sync issues on environments with multiple users
* Folders from other users will no longer appear on your Outlook

Fix sharing imap connections between different clients

---

OpenChange/MAPIStoreContext.m

[mapping registerURL ...] will insert the mappingId in indexing database
there is no need to call, again, mapistore_indexing_record_add_mid

oc: remove useless mapistore_indexing call

---

OpenChange/MAPIStoreMailVolatileMessage.m

Some clients such as OpenChange client does not send the following
properties PidTagNormalizedSubject or PidTagSubjectPrefix as
suggested by [MS-OXCMAIL].
If you think `NEWS` is valuable here, please advise the use of:
* Subject set while sending mails from simple MAPI clients.

oc-mail: Fallback to PidTagSubject unicode when creating new mail

---

OpenChange/MAPIStoreMailFolder.m
SoObjects/Mailer/SOGoMailFolder.m

This getter is necessary to decode folder names
in utf7 encoding.
Suggested message for NEWS:
- Non-latin folder names are displayed correctly on Outlook

oc-mail: Added [MAPIStoreFolder getPidTagDisplayName:inMemCtx:]

---

OpenChange/MAPIStoreFolder.m

As required by operations like SynchronizationImportHierarchyChanges
a new change number must be generated when a change in a folder
is set. This affects to subfolders.
See [MS-OXCFXICS] Section 3.2.5.9.4.3 for details.

oc: Update ChangeNumber after setting folder properties

---

SoObjects/SOGo/SOGoUserManager.m

Behaviour noticed in our tests: users couldn't log in through web interface (users use email as login).
The reason was that there was its information cached with `DomainLessLogin` set to true (so the user couldn't authenticate properly because sogo code was trying to authenticate using only `foo` instead of `foo@domain.com`).
The problem was that before doing this login the test performed some appointments operation with Outlook and there was when the information about the user was being cached incorrectly with `DomainLessLogin` due to a bad initialization of `[SOGoUser initWithLogin: @"foo"]`. With domain based uids (aka multidomain environment) you must initialize `SOGoUser` with `uid@domain` (remember uid is unique only inside the domain, no globally), if you initialize the `SOGoUser` …

SOGoUser bad initialization on multidomain environment

---

OpenChange/MAPIStoreDBMessage.m
OpenChange/MAPIStoreFolder.h
OpenChange/MAPIStoreFolder.m
OpenChange/MAPIStoreGCSFolder.h
OpenChange/MAPIStoreGCSFolder.m
OpenChange/MAPIStoreGCSMessage.m
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreSOGo.m
OpenChange/NSData+MAPIStore.h
OpenChange/NSData+MAPIStore.m

Before this, the `PidTagPredecessorChangeList` property value was not being updated with changes from the client in ROPs like `SetProperties` or `SynchronizationImportMessageMove`. By now, we are merging received property value with the updated values from the server's backend (IMAP server and SOGO DB).
This requires https://github.com/openchange/openchange/pull/359 to compile and work.
Suggested `NEWS`:
* Less conflicting messages in Outlook while moving messages between folders.

Maintain PidTagPredecessorChangeList with client's data

---

debian/control

This can only be merged when this two pull requests are merged and released:
https://github.com/Zentyal/zentyal/pull/1759
https://github.com/Zentyal/zinc-puppet/pull/129
So we move the responsibility of make sure that memcached is installed to the integrators instead of doing it in this package.

Remove memcached as a compulsory dependency and suggest it only

---

OpenChange/MAPIStoreMailFolder.h
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStoreMessage.m

After saving a draft mail (this is done automatically by Outlook)
a GetProps call is done checking the PidTagChangeKey has been
updated properly. Without this patch, it returned MAPI_E_NOT_FOUND.
With this patch, we addressed that problem and we have updated
the Predecessor Change List metadata for the draft mail with the
change key provided by the client to avoid conflicting messages
whenever it is possible.
NEWS line:
* Avoid conflicting message on saving a draft mail.
Example NDR output request:
```
mapi_request: struct EcDoRpc_MAPI_REQ
opnum                    : 0x0c (12)
logon_id                 : 0x00 (0)
handle_idx               : 0x00 (0)
u                        : union EcDoRpc_MAPI_REQ_UNION(case 12)
mapi_SaveChangesMessage: struct SaveChangesMessage_req
handle_idx …
```

oc-mail: Return right change key after saving a draft mail

---

OpenChange/MAPIStoreMailAttachment.m
OpenChange/MAPIStoreMailMessage.m

The attachments which used a extended parameter for their filename
('filename*=') where silently dropped.
This was because MAPIStore was only looking for no-extended filename
parameter.
The solution is using the 'filename' from the
SOGOExtension of the NSDictionary interface.

sogo-openchange: Support attachments with filename extended parameter

---

OpenChange/MAPIStoreCalendarMessage.m
OpenChange/MAPIStoreDBMessage.m
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreMessage.h
OpenChange/MAPIStoreMessage.m
OpenChange/MAPIStoreSOGo.m

This is an utility for testing as I don't see any added value
for real scenario but according to [MS-OXCMSG] all messages
can have PidTagMessageFlags.
Returned `enum mapistore_error` for `setReadFlag:flag` message has been done as well.

Implement setReadFlag for MAPIStoreDBMessage

---

OpenChange/MAPIStoreGCSFolder.m
OpenChange/MAPIStoreMailFolder.m

versionsMessage object could have outdated version in a root folder
in the following case:
* Download latest contents using FXBuffer
* versionsMessage is updated by synchroniseCache
* OpenMessage a new message after synching
* Setup versions message as root folder
* Get Predecessor Change List of that message
We could just reload if needed the versions message if something
is missing but I don't know if that situation fixes more than this
one.
The performance improvement comes from avoiding, at least, two IMAP calls when they are not required in this situation. A common one if you are receiving mails via notifications.

oc: load versionsMessage on setting up

---

OpenChange/MAPIStoreMailMessage.m

It is required when you are using `SynchronizeImportReadStateChanges` ROP
to update the `MetaTagCnsetRead` meta property.
See [MS-OXCFXICS] Section 3.2.5.9.4.6
This could lead to sync issues.
Update `NEWS`:
* Less sync issues when setting read flag

oc-mail: Increase Change Number after modifying seen flag

---

OpenChange/MAPIStoreMailAttachment.m
OpenChange/MAPIStoreMailMessage.m

The warnings were introduced in the fix for attachment with used
the filename extended parameter.
Also removed trailing whitespaces.

Fix some compilation warnings

---

debian/sogo.logrotate

We need this as sometimes postrotate script (/etc/init.d/sogo restart) is not able to successfully shut down sogo before restarting it. This has been tested in 1-2 customers and seems to fix the issue

Changed logrotate

---

SoObjects/SOGo/NSString+Utilities.m

A CSS identifier can't start with a digit, so when a folder name does,
a '_' character is appended at the beginning of its CSS identifier.
The check for this first character used the `isdigit()` function, which
takes a `char` argument, while `[self objectAtIndex: 0]` returns a
`unichar`, i.e. a 16-bit unsigned integer. This caused some non-digit
characters to pass this check (e.g. Chinese characters), ending up with
an underscore at the beginning of the folder name.
Update `NEWS`:
* Fix creation of root folders with Chinese characters

Improve first character check in CSS identifiers

---

OpenChange/MAPIStoreTasksMessage.m

It was not working because we try to save as component the
full calendar and its parent was nil. We have to save the calendar
itself to save the task in the personal calendar.
* Tasks created in Outlook are now saved and shown in SOGo UI

oc-task: Save tasks from Outlook

---

OpenChange/MAPIStoreDBMessage.m

See the commit messages for details, but basically not returning the FAI properties on a oxcfxics operation make Outlook crash after switching back to that folder.
`NEWS` suggested line:
* Avoid crashing Outlook after setting a custom view in a calendar folder

Avoid crashing Outlook after setting a custom view in a calendar folder

---

debian/control

It's no longer necessary becase md4.c was copied to the source

Remove gnulib build-dependency

---

OpenChange/MAPIStoreMailContext.m
Scripts/openchange_user_cleanup
SoObjects/Mailer/SOGoMailAccount.m
SoObjects/Mailer/SOGoMailFolder.m
UI/MailerUI/UIxMailFolderActions.m
UI/MailerUI/UIxMailMainFrame.m
UI/WebServerResources/MailerUI.js

The folder names are encoded through the `asCSSIdentifier` and
`stringByEncodingImap4FolderName` functions when we store them as folder
keys. In addition, the prefix "folder" is added to the key.
The order in which these operations were done when storing the folder
keys (and reverted when retrieving them) wasn't consistent trough the
code. This led to problems such as creating twice a folder with a digit
at the beginning of its name.
The folder name goes now through the following operations when being
stored as a key (the retrieval reverts these in the reverse order):
* `stringByEncodingImap4FolderName`
* `asCSSIdentifier`
* Add "folder" prefix
* Fix double creation of folders in OL when the folder name starts with a digit

Make folderKey encoding consistent 

---

SoObjects/Contacts/SOGoContactSourceFolder.m
UI/WebServerResources/UIxAttendeesEditor.js

When returning contacts we have to supply also the domain field.
Because in a multidomain environment UIDField is unique only in
the domain so an user must be identified as uid@domain.
So when creating http requests from client side, we have to use
uid@domain instead of only uid so the SOGoUser created on server
side when parsing the requests is created properly.
Message for `NEWS`
Freebusy on web interface works again in multidomain environments

Fix freebusy for multidomain environments

---

OpenChange/MAPIStoreMailVolatileMessage.m

This method returned true if the content id was a empty string.
In some case this triggered the removal of attachments when
sending messages.
NEWS:    Fix corner case that removes attachments on sending messages from Outlook

oc-mail: Fixed false positive in [MAPIStoreAttachment hasContentId]

---

SoObjects/SOGo/GCSSpecialQueries+SOGoCacheObject.m
SoObjects/SOGo/SOGoCacheGCSObject.m

This reduces considerably the query time for that column, which can be
rather large.
There is a separate PR for the trusty branch, https://github.com/zentyal/sogo/pull/192, that performs the DB migration for this change.

Store c_content in sogo_cache_folder as a BLOB

---

debian/sogo-openchange.postinst
debian/sogo.postinst

This is a migration for the changes in https://github.com/zentyal/sogo/pull/191, which change the type of the `c_content` column in the `sogo_cache_folder_foo` table from LONGTEXT to BLOB.

Include c_content as a BLOB in the migration

---

SoObjects/Appointments/SOGoAppointmentFolder.m

Happened in an imported vevent from Mozilla Thunderbird.
The crash was:
```
Sep 14 15:49:38 sogod [21063]: <0x6442DBF8[SOGoAppointmentFolder]:personal> missing 'c_startdate' in record?
Sep 14 15:49:38 sogod [21063]: <0x6442DBF8[SOGoAppointmentFolder]:personal> missing 'c_enddate' in record?
2015-09-14 15:49:38.927 sogod[21063] NGCalendarDateRange.m:37  Assertion failed in NGCalendarDateRange(instance), method initWithStartDate:endDate:.  startDate MUST NOT be nil!
EXCEPTION: <NSException: 0x7fb96b3c0ed8> NAME:NSInternalInconsistencyException REASON:NGCalendarDateRange.m:37  Assertion failed in NGCalendarDateRange(instance), method initWithStartDate:endDate:.  startDate MUST NOT be nil! INFO:(null)
```
The relevant ICS file lines are the following ones:
```
BEGIN:VEVENT …
```

Ignore recurrence-id vevents without dtstart and outside date range

---

SoObjects/SOGo/GCSSpecialQueries+SOGoCacheObject.m
SoObjects/SOGo/SOGoCacheGCSObject.m

This reverts commit b32951384568dc705d16cde4be910a886cb58b49. It was
causing issues and we'll need to do more testing on this optimisation.
This PR goes along with https://github.com/zentyal/sogo/pull/196

Revert "Store c_content in sogo_cache_folder as a BLOB"

---

debian/sogo.postinst

The optimisation caused issues and we'll remove it until it works
properly.
This PR goes along with https://github.com/zentyal/sogo/pull/197

Revert c_content as BLOB from the migration

---

OpenChange/MAPIStoreGCSFolder.h
OpenChange/MAPIStoreGCSFolder.m
OpenChange/MAPIStoreGCSMessage.m

Sometimes we're trying to get the `objectVersion` of a calendar message,
but this message's entry is not in the cache. The method
`synchroniseCache` won't work in this case, so we try to force the
synchronisation of that particular message in order to get the change
number before aborting.
Suggested `NEWS`:
* Avoid crashing when calendar metadata is missing in the cache

oc-calendar: force cache synchronisation for a message before aborting

---

OpenChange/MAPIStoreMailFolder.m
SoObjects/Appointments/SOGoAppointmentFolder.m

Two workarounds to avoid `NSException` as described in commit messages.
Suggested `NEWS` line in *Fixes* sections:
* Provide safe guards in mail and calendar to avoid exceptions while syncing

Workaround sync configure crashes

---

OpenChange/MAPIStoreUserContext.m
SoObjects/SOGo/SOGoObject.m

Fix cfab18e so user context is always activated when using userContextWithUsername method and add a log message to catch more operations when objects are created badly with woContext of the woApplication set to nil

User context activation when cached

---

OpenChange/MAPIStoreDBFolder.m
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreTypes.m
OpenChange/NSArray+MAPIStore.m

The changes in the exchange.idl file from OpenChange has changed
some string pointers from 'const char *' to 'uint8_t *'.
This changeset cast them to avoid compilation warnings.

sogo-openchange: Avoid compile warnings after changes in exchange.idl

---

OpenChange/MAPIStoreContactsMessage.m
OpenChange/MAPIStoreGCSMessage.m

This is a temporal solution until we have support of IMP.DistList. 
Not saving them avoid the creation of a incorrect contact in SOGo with the name of the distribution list. The member of the distribution list are correctly imported.
The distribution list created in SOGo are ignored.
Suggested NEWS line:
Avoid creation of phantom contacts in SOGo from distribution list synced from Outlook.

Do not save IPM.DistList messages

---

OpenChange/MAPIStoreAppointmentWrapper.m
OpenChange/MAPIStoreFolder.m
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreMailVolatileMessage.m
OpenChange/MAPIStorePermissionsTable.m
OpenChange/MAPIStoreSamDBUtils.h
OpenChange/MAPIStoreSamDBUtils.m

Adapt to new OpenChange safe method to avoid freeing
connInfo->samCtx without replacing it with a new one on
reconnect events

Adapt to new safe_ldb_search function

---

OpenChange/RTFHandler.h
OpenChange/RTFHandler.m

Several fixes:
- Better parsing of font table
- When using a font, switch to its character set
- Correct parsing of escaped characters
- Unicode character command word support for unicode characters greater than 32767

RTFHandler fixes with focus in unicode and characters set

---

OpenChange/MAPIStoreContactsMessage.m

Huge refactorization of `MAPIStoreContactsMessage.m` but the relevant changes that fix contacts are in 2a3367a where basically we add 3 new properties to be returned: `AddressBookProviderArrayType`, `AddressBookProviderEmailList` and `Email1OriginalEntryId`. The first ones are to know which of the emailX properties are defined.
Right now personal contacts (either created from SOGo webmail or from another instance of outlook) are really broken. This can be tested in many ways:
* Open a contact in outlook and try to close it, outlook will ask if you want to save changes (despite of no changes were made, this is because the contact is broken and needs more properties to be valid).
* Open your address book, change to personal addresses, the email of the contacts won't show up
* Try to send an …

Fix contacts on outlook

---

SoObjects/Mailer/NSDictionary+Mail.m

Some clients (like apple mail) use only the filename
attribute in the content/disposition header and the
name attribute from the content/type header is fill with
uninternationalized characters. Example: "___.rtf".
This changeset give priority to the filename attribute.

Priorize filename attribute first to get attachment name

---

OpenChange/MAPIStoreDBMessage.m
OpenChange/MAPIStoreDBMessageTable.m
OpenChange/MAPIStoreGCSFolder.m
OpenChange/MAPIStoreGCSMessageTable.m
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailMessageTable.m
OpenChange/MAPIStoreSOGoObject.m

Most of these changes make only sense along with https://github.com/zentyal/openchange/pull/189.
Along with the support to all kind of messages (Mail, GCS and DB) we have added several fixes:
* Use ReplicaID from connection info to build the `ChangeNumber` and `ChangeKey` properties
* Use NSString index for version lookup in GCS messages (Calendar, Task, Contacts) when searching for a last modified value using the Change Number
* Implement description method for `MAPIStoreDBMessage` to ease debugging.
The `NEWS` tip would be in `Enhancements` section:
* Return the requested elements on complex requests from Outlook when downloading changes

Manage multiple Change Number restrictions

---

OpenChange/GNUmakefile
OpenChange/dbmsgreader.m

Example:
```
{ 18 items
PidTagSubjectPrefix = (GSCBufferString) ,
PidTagSearchKey = (NSDataMalloc) <b97455a5 d2752443 8d56a69f 9da90f8c>,
PidTagLastModificationTime = (NSCalendarDate) 2015-12-10 06:41:04 -0800,
PidTagCreationTime = (NSCalendarDate) 2015-12-10 06:41:04 -0800,
PidTagNormalizedSubject = (GSCBufferString) IPM.Configuration.RssRule,
PidTagRoamingDatatypes = (NSIntNumber) 4,
PidTagMessageFlags = (NSIntNumber) 73,
0x685d0003 = (NSIntNumber) 785437,
PidTagSensitivity = (NSIntNumber) 0,
PidTagRtfInSync = (NSIntNumber) 1,
PidTagLastModifierName = (GSCBufferString) foo@foobar.lan,
PidTagRoamingDictionary = (NSDataMalloc) <3c3f786d 6c207665 7273696f 6e3d2231 2e30223f 3e0d0a3c 55736572 436f6e66 69677572 6174696f 6e3e0d0a 093c496e 666f2076 65727369 6f6e3d22 4f75746c 6f6f6b2e 3134222f …
```

oc: Dump property canonical name in dbmsgreader

---

OpenChange/MAPIStoreMailVolatileMessage.m

For example, if the SMTP is down, then the message is not sent and
an error is returned. We returned back this error code to be managed
by upper layer.
`NEWS` tip in *Fixes* section:
* Return an error if mail message delivery fails

oc-mail: Return error when delivery was not successful

---

OpenChange/MAPIStoreCalendarFolder.m
OpenChange/MAPIStoreContactsFolder.m
OpenChange/MAPIStoreDBFolder.m
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreTasksFolder.m

According to [MS-OXCPERM] Section 2.2.7 in PidTagMemberRights possible
values, once we set the DeleteAny flag, the DeleteOwned flag must be set.
Likewise EditOwned must be set when EditAny is set. In this way,
the rights sent by the MAPI client are equal to the returned by the
server when Editor is set.
In real world practice, makes more strict Outlook 2013 work with editor permissions
the sharing of user's defined calendars, tasks or contacts folders as
the recipients can be editors of that folder.
`NEWS` tip in `Fixes` section:
Share calendar, tasks and contacts folders in Outlook 2013 with editor permissions

oc: Set Editor as role is now possible in Outlook

---

OpenChange/MAPIStoreAppointmentWrapper.h
OpenChange/MAPIStoreAppointmentWrapper.m
OpenChange/MAPIStoreCalendarEmbeddedMessage.m
OpenChange/MAPIStoreCalendarMessage.m
OpenChange/MAPIStoreMailMessage.m
OpenChange/MAPIStoreRecurrenceUtils.h
OpenChange/MAPIStoreRecurrenceUtils.m
OpenChange/NSDate+MAPIStore.h
OpenChange/NSDate+MAPIStore.m
OpenChange/iCalEvent+MAPIStore.m
OpenChange/iCalTimeZone+MAPIStore.h
OpenChange/iCalTimeZone+MAPIStore.m

We were using the user time zone (the one in the webmail) by default, which caused shifts in the events when and the client one was different. This PR interprets the `TimeZoneDefinition` properties provided by the client and uses them to create and retrieve events.
* Suggested NEWS line:
`Fix shifts in event times`

oc-calendar: Use the time zone provided by the client

---

SoObjects/SOGo/NSString+Utilities.m

This uses https://github.com/zentyal/sope/pull/23 to encode properly the `subject` header of all emails (this affects both sogo web and outlook).

Fix encoding of subjects of emails with non-ascii characters

---

Tests/Unit/SOGoTest.m
Tests/Unit/SOGoTestRunner.h
Tests/Unit/SOGoTestRunner.m
Tests/Unit/sogo-tests.m

To integrate with CI system.
sogo-tests now accepts a flag (-f) to determine the output format:
* text : Current behaviour and default value
* junit: XML output suitable for CI system such as Jenkins

Give support to JUnit output format for sogo-tests

---

SoObjects/Mailer/SOGoDraftObject.m

Attachment creation can succeed and attachment mime file could fail
This can happen, e.g., when the filename's length is close to the maximum allowed but your filesystem and then mime file will exceed that limit (because it has a prefix).
Suggested line for `NEWS` the title of this pr.

Do not include failure attachments (really long filenames)

---

OpenChange/MAPIStoreCalendarFolder.m

Review and fixing all possible permission levels that could be assigned in a calendar folder:
* Editor role has been added
* Simple and Detailed Free/Busy permission level added
We have detailed in the code which permission flags are available in MAPI but it cannot be set in SOGo because the former are much more fine grained:
* DeleteOwned : Delete only own objects
* EditOwned : Edit only own objects
* CreateSubfolders: No calendar subfolders
* FolderOwner: No sharing folder ownership?
* FolderContact: No support to store this information
* FolderVisible: It is inferred by other rights when extracting
Tips for `NEWS` in `Enhancements` section:
* Editor role, Simple and Detailed Free/Busy permission level can be set in calendar folder permissions from Outlook.

Calendar folder permission roles

---

OpenChange/MAPIStoreAppointmentWrapper.m

For PidLidAppointmentTimeZoneDefinitionStartDisplay.
It is a typo introduced by 376e717f.

oc-calendar: Fix typo setting or operator

---

OpenChange/MAPIStoreSOGo.m

Get the current openchange log level (actually is the samba's log level)

Setting log level on backend initialization

---

OpenChange/MAPIStoreSOGo.m
SoObjects/Mailer/SOGoMailBaseObject.h
SoObjects/Mailer/SOGoMailBaseObject.m

By setting `SoIMAP4ExceptionsEnabled` config key to YES
Enabled for OpenChange by default, it will ensure no action is taken
when IMAP connection is not valid.
It would be desirable to release this change after https://github.com/zentyal/sope/pull/26 is released, as reconnect will cause too many open descriptors without that fix applied

Allow exception raising when connecting to IMAP

---

OpenChange/MAPIStoreContactsMessage.m

In `_getElement` which match many properties and in both
*PidLidAddressBookProviderEmailList* and *PidLidAddressBookProviderArrayType*.
As it is specified in [MS-OXOCNTC] Section 2.2.1, each property
must be stored when the user needs it. So we can assume we can avoid
returning them if we don't have it.
This fixes a Sync Issue which make it impossible to sync a contact
folder where some contact object does not any email. The sync issue
message is as follows:
Error synchronizing folder
[80070057-30FFFFFF-0-560]

oc-contacts: Return not found when there is no information

---

OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMailMessage.h
OpenChange/MAPIStoreMailMessage.m

With multipart messages only one of the parts was displayed as message body.
This changeset supports both mixed and alternative multipart types.

sogo-openchange: Support for multipart/mixed and multipart/alternative

---

SoObjects/SOGo/SOGoGroup.m

Using LDAP as source, the group entry must have a valid
group objectClass such as posixGroup or group and have a
valid UIDField which does not include the domain.
With this changeset, SOGo is aware of these groups when it has
an email and you can share a component such as a calendar with
the member of the group.
`NEWS` in *Enhancements* section:
* Support to groups for `EnableDomainBasedUID` configuration

Support for groups using EnableDomainBasedUID configuration

---

SoObjects/Appointments/SOGoAppointmentFolder.m

Instead of keeping only the highest access roles. This reverts
2c678101 to fix handling of ACLs with multiple groups.
This is done because OpenChange library stores other roles/permissions
in the ACLs that have limited scope to the MAPI protocol and it
maintains an homogeneous returned data with other folders by returning
the actual data is stored in the DB.
By sorting the roles, we give the ability to callers to validate
permissions more efficiency (less loops) and keep the right highest
access level. As an example, check
[SOGoApppointmentFolder:roleForComponentsWithAccessClass:forUser]
for details.
`NEWS` tips in **Fixes** section:
* Preserve all stored roles in Calendar folder ACLs to store custom MAPI-only permissions

Keep all roles in calendar folder ACLs

---

Tools/sogo-tool.m

This will ensure sogo-tool works when external plugins are needed

Ensure sogo-tool loads all available products

---

OpenChange/MAPIStoreMailMessage.h
OpenChange/MAPIStoreMailMessage.m
SoObjects/Mailer/SOGoMailObject.h
SoObjects/Mailer/SOGoMailObject.m

Instead of treating all the message either as alternative or mixed with
this changeset the MIME type of the parent part is used.
This allows a correct disposition of the message in the cases when
nested multiparts elements are used.
Also in mixed parts we convert between plain text and HTML as needed.

oc-mail: Better management of nested multipart types
