OpenChange/MAPIStoreContactsMessage.m

As specified by Microsoft using x-ms-anniversary custom vcard element
[MS-OXVCARD] Section 2.1.3.9.6

oc-contacts: Implement Wedding Anniversary

---

OpenChange/MAPIStoreMailFolder.m

This fixes sync issues when moving/deleting messages from one folder.

Sync deleted messages

---

OpenChange/MAPIStoreAppointmentWrapper.m

Ignore alarms discarded from sogo webmail

oc-appointments: ignore alarms already triggered

---

UI/WebServerResources/UIxPreferences.css
UI/WebServerResources/generic.css

Thanks to @jacarrion for some of them

Fix UI glitches in Preferences dialog when enabling new options

---

SoObjects/SOGo/SOGoUserManager.m

When users use full domain to login (SOGoEnableDomainBasedUID = YES) the user attributes in the cache were not being properly updated because in this case the key is `uid@domain` instead of just `uid`.
The behavior seen without this patch is that after you change your password you have to wait 300 seconds (default timeout of entries in memcached) until you are able to login again (or restart memcached).

Fix change password with multidomains

---

NEWS
OpenChange/MAPIStoreRecurrenceUtils.h
OpenChange/MAPIStoreRecurrenceUtils.m
OpenChange/iCalEvent+MAPIStore.m

* Fix exception modifications import in recurrence series
* Fix weekly recurring events exported to Outlook from SOGo
See the reasoning on the commit messages.

Two fixes on recurring events

---

OpenChange/MAPIStoreSharingMessage.m

It has been moved in OpenChange in https://github.com/openchange/openchange/pull/256

oc-mail: Update place for Sharing Flavour prop values

---

debian/sogo-activesync.postinst

And at the same time it is ready for Zentyal cloud product too.

Adapting posinst from sogo-activesync to new Zentyal Server

---

OpenChange/MAPIStoreFolder.h
OpenChange/MAPIStoreFolder.m
OpenChange/MAPIStoreMailFolder.m
OpenChange/MAPIStoreMessage.m
OpenChange/MAPIStoreMessageTable.m

Required for openchange-sogo plugin to compile with openchange/openchange PR #282

[oxcnotif] Delete deprecated notification code

---

NEWS

Please add a commit here with a new line each time you merge a Pull Request in master branch.

News updated with latest changes

---

SoObjects/Appointments/SOGoAppointmentObject.m

The UID was being used to check if  the changes in an appointment had been made by
its organiser. In this case, the UID is the user name, without taking the domain into account.
The `owner` variable, however, is a full email address, so the comparison was never successful. This
caused the update notification mail not to be sent.
`Appointment update notification mails are now sent`

oc-calendar: Improve check for appointment updates

---

NEWS

Add here latest changes in `master`.

Update NEWS from 2.2.17a-zentyal3

---

ActiveSync/SOGoActiveSyncDispatcher.m
SoObjects/SOGo/LDAPSource.m
SoObjects/SOGo/SOGoUserManager.m

Added 'ActiveSync' module constraint. If constraint is not
honored the ActiveSync request returns a no autorized error (403).
NEWS line suggestion:
Added 'ActiveSync' module constraint.

ActiveSync: can be controlled by module constraint

---

SoObjects/SOGo/SOGoUserManager.m

Agreed with @blaxter to remove this condition by request of @extrafu
Once the tests run I will merge it.

Remove not needed block in SoObjects/SOGo/SOGoUserManager.m

---

NEWS

Branch to update NEWS from 2.3.0-zentyal1 onwards

Update NEWS from 2.3.0-zentyal1

---

NEWS

Branch to update NEWS from 2.3.0-zentyal2 onwards

Update NEWS from 2.3.0-zentyal2

---

OpenChange/MAPIStoreMailMessageTable.m

And warn when other operator than > or >= is used.
This allows OpenChange to query for change numbers starting from
a given point.

oc-mail: Implement ChangeNumber >= restriction

---

UI/Scheduler/SpanishSpain.lproj/Localizable.strings

As current string was referring only to events

Changed Spanish string for view all (events/tasks)

---

OpenChange/MAPIStoreMailMessage.m

And perform the real IMAP operation on save method as described by
[MS-OXCFXICS] and [MS-OXCMSG] Section 2.2.3.3, these operations must be
committed when SaveChangesMessage is called.
As it is expected by Outlook to increase the change number when
performing the `SetMessageReadFlag` ROP, if it is not done, the client
tries indefinitely to store that.
* Avoid infinite Outlook client loops trying to set read flag when it is already set

oc-mail: Always increase the CN when setting the message read flag

---

OpenChange/MAPIStoreMailFolder.m

There is a use case where this has caused crashes:
A message was hard-deleted using an IMAP client, this is the first
message you deleted in that folder and you have cleared offline
items in the client so a full sync is asked by upper layer.
In that situation, the SyncLastDeleteChangeNumber version property
is not set and return 0 in [getDeletedKeysFromChangeNumber:andCN:inTableType]
making OpenChange to crash while it is asking for deleted fmids
since a given change number.
This is a regression from 18d7070c4a44a8437.
Suggested `NEWS` line in `Fixes` Section:
* Fix corner case making server crash when syncing hard deleted messages when clear offline items was set up.

oc-mail: Sync expunged messages on first cache sync

---

OpenChange/MAPIStoreMailMessage.m

SOGo event notification mails add information to the event name in their
subject (e.g. _Event invitation: "foo"_). The client uses the mail
subject to create a copy of the event on the attendee's calendar, so we
need to strip out that extra information if we want the event to have
the proper name.
* Accepted & updated event names are now shown correclty

oc-calendar: Make invitation/update mails have the event name as subject

---

OpenChange/MAPIStoreMailVolatileMessage.m

After the providing the workaround on rebuilding the LDAP connection,
the sam_ctx variable can be freed and it was used as memory context
to store the AddressBookEntryId or OneOffEntryId when resolving
recipients. After this changeset, a local memory context which I
think is more sane.
`NEWS` tip:
* No crash resolving recipients after reconnecting LDAP connection

oc-mail: Do not crash after reconnect sending mails

---

SoObjects/Contacts/SOGoContactSourceFolder.m
SoObjects/SOGo/GNUmakefile
SoObjects/SOGo/LDAPSource.h
SoObjects/SOGo/LDAPSource.m
SoObjects/SOGo/SOGoDomainDefaults.m
SoObjects/SOGo/SOGoGroup.m
SoObjects/SOGo/SOGoSession.m
SoObjects/SOGo/SOGoSource.h
SoObjects/SOGo/SOGoSystemDefaults.m
SoObjects/SOGo/SOGoUser.m
SoObjects/SOGo/SOGoUserManager.h
SoObjects/SOGo/SOGoUserManager.m
SoObjects/SOGo/SQLSource.m
Tools/SOGoToolBackup.m

This change unifies user sources API and allows new user sources to be loaded dynamically

Unify user sources API

---

UI/WebServerResources/UIxAttendeesEditor.js

Syntax error after merging upstream in attendees editor because of our restyled UI

Fix attendees editor after 2.3.3a upstream merge

---

UI/WebServerResources/ContactsUI.js

Otherwise we receive an empty response.
This will conflict with our trusty branch, the issue is also on inverse-inc/sogo so I think is better to merge it to master (so it can be on upstream eventually), when we performed our ui-restyle this was fixed (wrongly) with an unnecessary if condition (that crashes).

Request all contacts when there is no filter

---

OpenChange/MAPIStoreSamDBUtils.m

As requested by @extrafu to maintain sogo packages for a little while until standard 4.3 packages will be used by OpenChange.

oc: Do compile with Samba 4.1

---

SoObjects/Appointments/iCalPerson+SOGo.m

This method is used to get the login and we weren't returning the
domain, which led to problems when creating appointments like, for
instance, not sending the invitation mails.
The patch is actually by @blaxter, so kudos to him.
* Fix appointment notification mails

Add the domain in the `uidInDomain` method

---

OpenChange/MAPIStoreSOGo.m

When exiting a library function

oc: Print retval on high debug for library interface

---

SoObjects/Contacts/SOGoContactSourceFolder.m
SoObjects/SOGo/LDAPSource.h
SoObjects/SOGo/LDAPSource.m
SoObjects/SOGo/SOGoSource.h
SoObjects/SOGo/SQLSource.m
UI/WebServerResources/ContactsUI.js

Removes listRequiresDot option, magically fixes contact listing (with and without filters)

Fix contact listing properly

---

OpenChange/MAPIStoreMailMessage.m

If we have multiple parts with different encodings we recode
all HTML parts to UTF-8 and we use it as message charset.
This is neccesary because Outlook assummessa single charset
for all the message.
Also we convert the end of line in text/plain to <br/> tag
when showing them as HTML in multipart/mixed parts.
Suggested NEWS line:
- Enforce UTF-8 in multipart with different encodigns

oc-mail: Use UTF-8 when there are parts with multiple charsets 
